const moduloA = require('./moduloA')
const moduloB = require('./moduloB')

console.log(moduloA)
console.log(moduloA.ola)
console.log(moduloA.bemVindo)
console.log(moduloA.ateLogo)
console.log()
console.log(moduloB)
console.log(moduloB.bomDia)
console.log(moduloB.boaNoite())
